Bibliotek_Labb1/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Bibliotek_Labb1.Models
{
    public class Book
    {
        [Key]
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public string ImageThumbnailUrl { get; set; }
        public string Description { get; set; }
        public bool IsOnLoan { get; set; }
        public ICollection<CustomerBook> CustomerBook { get; set; }
    }
}

Bibliotek_Labb1/Controllers/BookController.cs
using Bibliotek_Labb1.Models;
using Bibliotek_Labb1.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bibliotek_Labb1.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;

        public BookController(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }

        public ViewResult List()
        {
            return View(_bookRepository.GetAllBooks);
        }

        public IActionResult Details(int id)
        {
            var book = _bookRepository.GetBookById(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }
    }
}

Bibliotek_Labb1/Controllers/CustomerBookController.cs
using Bibliotek_Labb1.Models;
using Bibliotek_Labb1.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bibliotek_Labb1.Controllers
{
    public class CustomerBookController : Controller
    {
        private readonly ICustomerBookRepository _loan;
        private readonly AppDbContext _appContext;

        public CustomerBookController(ICustomerBookRepository loan, AppDbContext appContext)
        {
            _loan = loan;
            _appContext = appContext;
        }

        public IActionResult CustomerBookLog(int id)
        {
            var cb = _loan.GetCustomerBookByID(id);
            return View(cb);
        }

        [HttpGet("{id}")]
        public IActionResult CustomerBookLogs(int id)
        {
            var cus = _appContext.CustomerBooks.FirstOrDefault(cb => cb.CustomerID == id);
            if(cus == null)
            {
                return NotFound("Not Loans Found");
            }
            else if (cus.CustomerID == id)
            {
                var loans = _appContext.CustomerBooks.Include(b => b.Book).Where(c => c.CustomerID == id);
                var customerLogViewModel = new CustomerLogViewModel()
                {
                    CustomerLoans = loans
                };
                return View(customerLogViewModel);
            }
            return View();
        }


        public IActionResult LoanBook()
        {
            var loans = _appContext.CustomerBooks.Include(b => b.Book);
            var customerLogViewModel = new CustomerLogViewModel()
            {
                CustomerLoans = loans
            };
            return View(customerLogViewModel);
        }

        [HttpPost]
        public async Task<ActionResult<CustomerBook>> AddLoanedBook(CustomerBook customerBook)
        {
            var newCustomerBook = await _loan.Add(customerBook);
            CreatedAtAction(nameof(CustomerBookLog), new { id = customerBook.CustomerBookID }, newCustomerBook);
            return View();
        }

    }
}

Bibliotek_Labb1/Controllers/CustomerController.cs
using Bibliotek_Labb1.Models;
using Bibliotek_Labb1.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bibliotek_Labb1.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _customerRepository;
        private readonly AppDbContext _appContext;
        public CustomerController(ICustomerRepository customerRepository, AppDbContext appContext)
        {
            _customerRepository = customerRepository;
            _appContext = appContext;
        }

        public ViewResult List()
        {
            return View(_customerRepository.GetAllCustomers);
        }

        public IActionResult CustomerInfo(int id)
        {
            var customer = _customerRepository.GetCustomerBytId(id);

            var cInfoViewModel = new CustomerInfoViewModel()
            {
                CustomerInfo = customer
            };
            return View(cInfoViewModel);
        }

        //Add New Customer
        [HttpPost]
        public async Task<ActionResult<Customer>> AddCustomer(Customer customer)
        {
            var newCustomer = await _customerRepository.Add(customer);
            CreatedAtAction(nameof(CustomerInfo), new { id = customer.CustomerID }, newCustomer);
            return View();
        }

        public IActionResult CreateCustomer()
        {
            return View("AddCustomer");
        }

        //Edit Customer

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCustomer(Customer customer)
        {
            _appContext.Update(customer);
            _appContext.SaveChanges();
            return RedirectToAction(nameof(List));

        }

        public IActionResult UpdateCustomer(int id)
        {
            var customer = _customerRepository.GetCustomerBytId(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }


        //Delete Customer Controller
        public async Task<IActionResult> DeleteCustomer(int id)
        {
            await _customerRepository.Delete(id);
            return View();
        }
    }
}

Bibliotek_Labb1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bi~Bibliotek</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bi~Bibliotek</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="List">All Books</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="List">Clients</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerBook" asp-action="LoanBook">Loan A Book</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bi~Bibliotek - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Bibliotek_Labb1/Views/Shared/_books.cshtml
@model Book

    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="@Model.ImageThumbnailUrl" alt="Book Cover Image" />

            <div class="caption">
                <h2><a asp-controller="Book" asp-action="Details" asp-route-id="@Model.BookID">@Model.BookName</a></h2>
                <h4>@Model.Author</h4>
            </div>
        </div>
    </div>